# Copyright 2017 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
#
# from github, overriding the name and specifying a specific tag
- src: https://github.com/vmware/ansible-role-pip
  version: master
  name: pip
